jwt.token.secret: "z/xQdiS1AsGssL+9p8/aJczQEIFdzYzAj3XSamNdsSU="
emailVerificationMessage: Thanks for signing up at Todo app.\nPlease click the following link to verify your email.
##########################################################
# This for database connection

spring:
    jpa:
        properties:
            hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
        hibernate:
            ddl-auto: validate
            show-sql: true
    datasource:
        url: "jdbc:postgresql://localhost:5432/todo"
        username: myuser
        password: 123456
##############################################################################